from typing import List

from pydantic import BaseModel, Field


class Message(BaseModel):
    message: str=Field(..., description="The message of the user asked in context with the documents uploaded")


class LLM_Response(BaseModel):
    result: str=Field(description="The response generated by the LLM based on the user query and the relevant chunks retrieved from the vector store",default="")
    bullets:List[str]=Field( description="The list of relevant bullet points extracted from the response to be sent to the frontend for better rendering and user experience", default=[])  