import os
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langgraph.graph import START, StateGraph
from langgraph.types import Command, interrupt
from typing import Literal
from langgraph.checkpoint.memory import MemorySaver
from uuid import uuid4
from .schema import Email, Review
from .gmail_service import send_email

# intialization of apikey, graph and memory
load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__),".env"))
llm_openai = ChatOpenAI(model="gpt-5-nano",temperature=0)
llm_openai_structured = llm_openai.with_structured_output(Email)
checkpointer = MemorySaver()

# intitialize graph
def create_graph(schema):
    graph = StateGraph(schema)
    graph.add_node("draft_email_node",draft_mail_node)
    graph.add_node("approval_node",approval_node)
    graph.add_edge(START,"draft_email_node")
    graph.add_edge("draft_email_node","approval_node")
    return graph.compile(checkpointer=checkpointer)


    
# node create draft
def draft_mail_node(state:Email)->Email:
    user_query = state.message
    llm_draft = state.draft_mail
    user_feedback = state.feedback
    prompt = ChatPromptTemplate.from_messages([
        ('system','You are a helpful email draft generator. Generate a draft for: {user_query}. If feedback exists, improve the existing draft: {llm_draft} based on this feedback: {user_feedback}'),
        ('human','Here is my query:{user_query}. Here is my feedback on your draft:{user_feedback}')
    ])
    chain = prompt | llm_openai_structured
    response = chain.invoke({"user_query":user_query,"llm_draft":llm_draft,"user_feedback":user_feedback})
    state.draft_mail = response.draft_mail
    return state



# node for approval
def approval_node(state:Email)->Command[Literal["draft_email_node","__end__"]]:
    decision = interrupt({
        "question": "Approve the draft?",
        "details": state.draft_mail,
    })

    # if decision["approval"]== "yes":
    #     return Command(goto="__end__",update={"approval":"yes"})
    if decision["approval"]== "yes":
         send_email(
        to="prashantnath6307@gmail.com",  # for now hardcode
        subject="Generated by GBOT",
        body=state.draft_mail
    )
         return Command(goto="__end__",update={"approval":"yes"})
    else:
        return Command(
            goto="draft_email_node",
            update={"feedback": decision["feedback"],"approval":"no"}
        )


# node to re-create draft based on approval
def review_email_draft(state:Review):
    id = state.id
    approval = state.approval
    feedback = state.feedback
    config = {"configurable":{"thread_id":id}}
    result = GRAPH.invoke(Command(resume={"approval":approval,"feedback":feedback}),config=config)
    if result["approval"] == "no":
        return {
            "message":result["message"],
            "new_draft_mail":result["draft_mail"],
            "approval":result["approval"],
            "feeback":result["feedback"],
            "question":"Are you now satisfied with the draft?",
            "id":id
        }
    elif result["approval"] == "yes":
        return{
            "message":result["message"],
            "final_draft_mail":result["draft_mail"],
            "approval":result["approval"],
            "last_feedback":result["feedback"],
            "id":id
        }

# fn invocation to create draft
def create_email_draft(state:Email)->dict:
    message = state.message
    thread_id = str(uuid4())
    config = {"configurable": {"thread_id": thread_id}}
    result = GRAPH.invoke(Email(message=message),config=config)
    
    interrupt_data = result["__interrupt__"][0].value
    return {
        "message":result["message"],
        "draft":result["draft_mail"],
        "approval":result["approval"],
        "feedback":result["feedback"],
        "id":thread_id,
        "question":interrupt_data["question"]
    }


# intitalize graph & checkpointer
GRAPH = create_graph(Email)
# testing mermaid
# print(GRAPH.get_graph().draw_mermaid())